name: NDK build

env:
  module_id: cinema
  qmodName: Cinema
  cache-name: Cinema_cache

on:
  push:
    branches: [ main, dev, ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        submodules: true
        lfs: true

    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Get QPM
      uses: Fernthedev/qpm-action@v1
      with:
        resolve_ndk: true
        #required
        workflow_token: ${{secrets.GITHUB_TOKEN}}
        cache: true #will cache dependencies

    - name: Restore
      run: |
        cd ${GITHUB_WORKSPACE}
        qpm restore

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        pwsh -Command ./build.ps1 -release
        qpm qmod build

    - name: Copy extra libs to extern/libs
      run: |
        mkdir -p extern/libs
        cp -r third_party/cpython/lib/* extern/libs/

    - name: Create Qmod
      run: |
        pwsh -Command ./createqmod.ps1 ${{env.qmodName}} -release

    - name: Get Library Name
      id: libname
      run: |
        cd ./build/
        pattern="lib${module_id}*.so"
        files=( $pattern )
        echo "NAME=${files[0]}" >> ${GITHUB_OUTPUT}

    - name: Upload non-debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.libname.outputs.NAME }}
        path: ./build/${{ steps.libname.outputs.NAME }}
        if-no-files-found: error

    - name: Upload libpython3 artifact
      uses: actions/upload-artifact@v4
      with:
        name: libpython3.so
        path: ./third_party/cpython/lib/libpython3.so
        if-no-files-found: error

    - name: Upload qmod artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.qmodName}}_0.0.1.qmod
        path: ./${{ env.qmodName }}_0.0.1.qmod
        if-no-files-found: error

    - name: Upload debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug_${{ steps.libname.outputs.NAME }}
        path: ./build/debug/${{ steps.libname.outputs.NAME }}
        if-no-files-found: error
    # TODO: Add auto-populating releases, auto update versions, auto publish package on release
